import type { AanbodContent } from '@/types/aanbod';
import type { HomeContent } from '@/types/home-content';

/** Merge target when Sanity is connected — no copy from JSON/dev bundles. */
export const EMPTY_HOME_CONTENT: HomeContent = {
  hero: {
    titleLine1: '',
    titleLine2: '',
    titleEm: '',
    claim: '',
    sub: '',
    primaryCta: '',
    secondaryCta: '',
  },
  diagnosis: {
    spine: '',
    headlineEm: '',
    p1: '',
    focus: '',
  },
  approach: {
    spine: '',
    headline: '',
    headlineEm: '',
    note1: '',
    introHl: '',
    stepPrefix: '',
    steps: [],
  },
  proof: {
    spine: '',
    headline: '',
    headlineEm: '',
    featured: {
      client: '',
      title: '',
      line1: '',
      line2: '',
      line3: '',
    },
    minis: [],
  },
  selection: {
    spine: '',
    headline: '',
    headlineEm: '',
    forItems: [],
    notForLabel: '',
    notFor: [],
  },
  about: {
    spine: '',
    headline: '',
    headlineEm: '',
    statement: '',
    creds: '',
    signature: '',
    quote: '',
  },
  offer: {
    spine: '',
    name: '',
    body: '',
    ctaPrimary: '',
    secondaryHlBeforeEm: '',
    secondaryHlEm: '',
    secondaryBody: '',
    secondaryNote: '',
  },
};

export const EMPTY_AANBOD_CONTENT: AanbodContent = {
  meta: { title: '', description: '' },
  hero: {
    headlineLine1: '',
    headlineLine2Em: '',
    sub: '',
    primaryCta: '',
    secondaryCta: '',
    offerFrame: { label: '', pillars: [] },
  },
  offerClarity: {
    eyebrow: '',
    leftTitle: '',
    leftBody: '',
    rightTitle: '',
    rightLead: '',
    forBody: '',
    welLabel: '',
    welItems: [],
    notForLabel: '',
    notForItems: [],
  },
  whatYouGet: {
    eyebrow: '',
    headline: '',
    subline: '',
    items: [],
  },
  howItWorks: {
    headline: '',
    stepPrefix: '',
    steps: [],
  },
  whatAfter: {
    eyebrow: '',
    headline: '',
    body: '',
    items: [],
  },
  pricing: {
    spine: '',
    name: '',
    priceLine: '',
    body: '',
    includedTitle: '',
    includedItems: [],
  },
  reassurance: { headline: '', body: '', note: '' },
  closing: { line1: '', line2: '', ctaLabel: '' },
};
